#21 add sendgrid for sending emails
ECE493W2021T3/eVoter pull request #40
Opened 2021-03-21 02:17 UTC by gatilogo

[//]: # (These are comments and are used for reference and will not show up in the PR)

**Description:** 

[//]: # (Include a summary of the change and which issue is fixed. List any dependencies that are required for this change)

Setup email service in backend by adding Send Grid for sending email functionality

**Proof of concept:**
![image](https://user-images.githubusercontent.com/55599387/111891478-058cca00-89b9-11eb-8347-79627113d708.png)

[//]: # (Replace with your issue id to automatically close given issue number upon closing PR)
Closes #21

2021-03-21 03:36 UTC, LiyaoJiang1998 approved these changes
email service looks good!

2021-03-22 05:59 UTC, gza060625 commented
Change mailer.js into one "service"
- Expose mailer method which sends email
- Expose `validateEmail()` and `setKey()`
- Add email message validator
- Add extra field "Intention" to email
- Add email messages for sent and not sent
- fix some EOF warning
- move mailer to services folder

Ask for review due to the changes @LiyaoJiang1998 
@gatilogo Couldn't add you as one reviewer, please have a look as well.

2021-03-22 06:07 UTC, gza060625 approved these changes
LGTM

2021-03-22 06:35 UTC, gza060625 submitted a review, later dismissed

2021-03-22 06:38 UTC, LiyaoJiang1998 requested changes

2021-03-22 06:38 UTC, LiyaoJiang1998 commented on backend/services/mailer.js
> +    intention:Joi.string().valid('Invitation', 'F2A', 'Access Code').required(),
```suggestion
    intention:Joi.string().valid('Invitation', '2FA', 'Access Code').required(),
```

2021-03-22 06:38 UTC, LiyaoJiang1998 commented on backend/services/mailer.js
> +    html: Joi.string().required(),
Just noticed when testing: when `html` is used, the content of `text` seems not used in email.

2021-03-22 06:40 UTC, LiyaoJiang1998 approved these changes

2021-03-22 06:41 UTC, LiyaoJiang1998 commented
LGTM, just fixed a typo. Tested that sending and validating works.

2021-03-22 07:11 UTC, gatilogo commented
> @gatilogo Couldn't add you as one reviewer, please have a look as well.

LGTM

2021-03-22 15:21 UTC, gza060625 approved these changes

2021-03-22 15:21 UTC, merged